DROP TABLE IF EXISTS `newscate`;
CREATE TABLE `newscate` (
 `cate_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
 `cate_name` VARCHAR(50) NOT NULL,
 `cate_title` VARCHAR(50) NOT NULL, PRIMARY KEY (`cate_id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;